name: Allison Von Borstel 
tagline: Analyst, Strategist, Consultant
background: michael-d-beckwith-579366-unsplash.jpg
bio: >
    This section is coming soon!

twitter: allisonvonb
github: avonborstel 
linkedin: allisonvonborstel 
